spring:
  application:
    name: gateway-server
  cloud:
    discovery:
      enabled: true
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
          corsConfigurations:
            '[/**]':
                allowedOrigins: "*"
                allowedMethods: "*"
                allowedHeaders: "*"
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
          # http://localhost:5555/marketplace/v1/auth/login
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/marketplace/*/auth/**

          # http://localhost:5555/marketplace/v1/product/{id}
        - id: ms-product
          uri: lb://ms-product
          predicates:
            - Path=/marketplace/*/product/**
        - id: ms-order
          uri: lb://ms-order
          predicates:
            - Path=/marketplace/*/order/**,/marketplace/*/cart/**
    loadbalancer:
      ribbon:
        enabled: false


eureka:
  client:
    fetch-registry: true
    service-url.defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

server:
  port: 5555