spring:
  application:
    name: zuul-server
server:
  port: 5555
  servlet:
    context-path: /marketplace
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

# http"//localhost:5555/cloud[/endpoint/]
zuul:
  routes:
    ms-auth: /auth/**
    ms-order: /order/**
    ms-product: /product/**
    ms-payment: /payment/**
    ms-storage: /storage/**
  sensitiveHeaders: Cookie, Set-Cookie
# ribbon:
#   ReadTimeout: 60000