server:
  port: 8193
  servlet:
    context-path: /marketplace
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product_db?currentSchema=product_sh
    username: postgres
    password: 1qaz@WSX
  session:
    store-type: redis
    jdbc:
      initialize-schema: always
    timeout:
      second: 900
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      show_sql: true
  flyway:
    enabled: true
  redis:
    host: localhost
    port: 6379



