server:
  port: 8194
  servlet:
    context-path: /marketplace/storage
spring:
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      ddl-auto: create-drop
      show_sql: true
      temp:
        use_jdbc_metadata_defaults: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/storage_db?currentSchema=storage_sh
    username: postgres
    password: 1qaz@WSX
  flyway:
    enabled: true
