spring:
  session:
    store-type: redis
    redis:
      host: localhost
      port: 6379
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      ddl-auto: create-drop
      show_sql: true
      temp:
        use_jdbc_metadata_defaults: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_db?currentSchema=user_sh
    username: postgres
    password: 1qaz@WSX
  flyway:
    enabled: true
    location: classpath:/db/migration/market/mscore
jwt:
  secret: 1q2w3e4r